language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v