language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ru

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v